words = {
  objects: [
	"Sash window",
	"Honeycomb",
	"Armchair",
	"Lego",
	"Dictionary",
	"Radiator",
	"Thesaurus",
	"Suitcase",
	"Zip",
	"Padlock",
	"D-lock",
	"Roller Blind",
	"Belt",
	"Hoodie",
	"Blanket",
	"Pannier",
	"Reflector",
	"Dynamo",
	"Clothes Horse",
	"Envelope",
	"Post-it note",
	"Blutack",
	"Plasticene",
	"Holdall",
	"Overhead locker",
	"Lightbulb",
	"LED",
	"Chocolate",
	"Cream Egg",
	"Jazzies",
	"Rhubarb and Custard",
	"Dolly Mixture",
	"Liquorice Allsorts",
	"Treacle Toffee",
	"Bonbon",
	"Gobstopper",
	"Chocolate Frog",
	"Uniform",
	"Reef knot",
	"Sheepshank",
	"Figure of eight",
	"Oil paint",
	"Watercolour",
	"Acrylic",
	"Emulsion",
	"Charcoal",
	"Pine needle",
	"Chalk Pastels",
	"Viola",
	"Cello",
	"Double Bass",
	"Harp",
	"Bassoon",
	"Flute",
	"Clarinet",
	"Trombone",
	"Tuba",
	"Timpani",
	"Snare Drum",
	"Cymbals",
	"Bloody Mary",
	"Singapore Sling",
	"Screwdriver",
	"Chorizo ",
	"Elderflower Cordial",
	"Sparkling water",
	"Meat Feast",
	"Camembert",
	"Cornish Yarg",
	"Goats Cheese",
	"Roquefort",
	"Gouda",
	"Paneer",
	"Halloumi",
	"Mascarpone",
	"Parmesan",
	"Emmental",
	"Edam",
	"Mixed peel",
	"Glacé cherries",
	"Free range eggs",
	"Demerara sugar",
	"Muscavado sugar",
	"Agave nectar ",
	"Maple syrup",
	"​​Cider vinegar",
	"​Dijon mustard",
	"Bicarbonate of soda",
	"Fruit and fibre",
	"Bircher muesli",
	"Sage and onion stuffing",
	"Earl grey tea",
	"Refried beans",
	"Mushy peas",
	"Sea salt",
	"Stock cubes",
	"Strawberry conserve ",
	"Alphabet spaghetti",
	"Self raising flour ",
	"Spirali",
	"Tagliatelle ",
	"Rice noodles",
	"Singapore noodles",
	"Chinese five spice",
	"Cocoa powder",
	"Vanilla essence",
	"Sesame oil "
  ]
}

