words = {
  Object: [
    "Sash window",
    "Honeycomb",
    "Armchair",
    "Lego",
    "Dictionary",
    "Radiator",
    "Thesaurus",
    "Suitcase",
    "Zip",
    "Padlock",
    "Dlock",
    "Roller Blind",
    "Belt",
    "Hoodie",
    "Blanket",
    "Pannier",
    "Reflector",
    "Dynamo",
    "Clothes Horse",
    "Envelope",
    "Postit note",
    "Blutack",
    "Plasticene",
    "Holdall",
    "Overhead locker",
    "Lightbulb",
    "LED",
    "Chocolate",
    "Cream Egg",
    "Jazzies",
    "Rhubarb and Custard",
    "Dolly Mixture",
    "Liquorice Allsorts",
    "Treacle Toffee",
    "Bonbon",
    "Gobstopper",
    "Chocolate Frog",
    "Uniform",
    "Reef knot",
    "Sheepshank",
    "Figure of eight",
    "Oil paint",
    "Watercolour",
    "Acrylic",
    "Emulsion",
    "Charcoal",
    "Pine needle",
    "Chalk Pastels",
    "Viola",
    "Cello",
    "Double Bass",
    "Harp",
    "Bassoon",
    "Flute",
    "Clarinet",
    "Trombone",
    "Tuba",
    "Timpani",
    "Snare Drum",
    "Cymbals",
    "Bloody Mary",
    "Singapore Sling",
    "Screwdriver",
    "Chorizo ",
    "Elderflower Cordial",
    "Sparkling water",
    "Meat Feast",
    "Camembert",
    "Cornish Yarg",
    "Goats Cheese",
    "Roquefort",
    "Gouda",
    "Paneer",
    "Halloumi",
    "Mascarpone",
    "Parmesan",
    "Emmental",
    "Edam",
    "Mixed peel",
    "Glac cherries",
    "Free range eggs",
    "Demerara sugar",
    "Muscavado sugar",
    "Agave nectar",
    "Maple syrup",
    "Cider vinegar",
    "Dijon mustard",
    "Bicarbonate of soda",
    "Fruit and fibre",
    "Bircher muesli",
    "Sage and onion stuffing",
    "Earl grey tea",
    "Refried beans",
    "Mushy peas",
    "Sea salt",
    "Stock cubes",
    "Strawberry conserve",
    "Alphabet spaghetti",
    "Self raising flour",
    "Spirali",
    "Tagliatelle",
    "Rice noodles",
    "Singapore noodles",
    "Chinese five spice",
    "Cocoa powder",
    "Vanilla essence",
    "Sesame oil",
  ],
  Nature: [
    "Spider plant",
    "Silver birch",
    "Clematis",
    "Wisteria",
    "Bluebell",
    "Stamen",
    "Coffee bean",
    "Brussel Sprout",
    "Parsley",
    "Kale",
    "Maris Piper",
    "King Edward",
    "Precipitation",
    "Eruption",
    "Meteor",
    "Halley's Comet",
    "Wren",
    "Orangutan",
    "Shetland Pony",
    "Lungs",
    "Kidneys",
    "Beard",
    "Toenail",
    "Metatarsal",
    "Metacarpal",
    "Hormones",
    "Insulin",
    "Pancreas",
    "Kidneys",
    "Buttock",
    "Reproduction",
    "Giant Squid",
    "Cuttlefish",
    "Barn Owl",
    "Blue Tit",
    "Mallard",
    "Quail",
    "Jay",
    "Wood Pigeon",
    "Swallow",
    "Turmeric",
    "Cinnamon",
    "Chilli",
    "Coriander seeds",
    "Cumin",
    "Smoked paprika",
    "Allspice",
    "Nutmeg",
    "Cayenne pepper",
    "Ground mace",
    "Lemongrass",
    "Lime leaves",
    "Marjoram",
    "Jackfruit",
    "Pinto beans",
    "Arborio rice",
    "Jasmine rice",
    "Pearl barley",
    "Bulgar wheat",
    "Basmati rice",
  ],
  World: [
    "Fulbourn",
    "Sawston",
    "Cairngorms",
    "River Thames",
    "Tower of London",
    "The Shire",
    "Mordor",
    "St Andrews",
    "Toad Hall",
    "Tate Modern",
    "Wuthering Heights",
    "Pyramids",
    "Babylon",
    "Costa Rica",
    "Baker Street",
    "Euston Square",
    "King's Cross",
    "Barbican",
    "Moorgate",
    "Victoria station",
    "St James's Park",
    "Tower Hill",
    "Notting Hill",
    "Westminster Abbey",
    "Embankment",
    "Aldgate",
    "Gloucestershire",
    "Manhatten",
    "Stilton",
    "Hogwarts",
    "Springfield",
    "Rivendell",
    "Asgard",
    "Neverland",
    "Gotham city",
    "The Emerald City",
    "Hogsmeade",
    "Diagon Alley",
    "Narnia",
    "Kings Landing",
    "Lilliput",
    "Godrics Hollow",
    "Jurassic Park",
    "Toyland",
    "Central Perk",
    "Middle earth",
    "Atlantis",
    "The Underworld",
    "Angkor",
    "Taj Mahal",
    "Machu Picchu",
    "Mount Rushmore",
    "St Basils Cathedral",
    "The Acropolis",
    "Easter Island",
    "The Western Wall",
    "Blue Mosque",
    "Giants causeway",
    "Petra",
    "Stonehenge",
    "Mount Fuji",
    "Matterhorn",
    "Victoria Harbour",
    "Times Square",
    "Forbidden city",
    "Disneyland",
    "Red square",
  ],
  Person: [
    "Toad",
    "Baby Peach",
    "Luigi",
    "Yoshi",
    "Rapunzel",
    "Elsa",
    "Baby Mario",
    "Mulan",
    "Tiana",
    "Tinker Bell",
    "Princess Jasmine",
    "Cinderella",
    "Ariel",
    "Belle",
    "Esmerelda",
    "Miss Piggy",
    "Kermit",
    "Micky mouse",
    "Minney mouse",
    "Donald Duck",
    "Goofy",
    "Captain Jack Sparrow",
    "Winnie the Pooh",
    "WallE",
    "Quasimodo",
    "Cruella de Vil",
    "Dumbo",
    "Grumpy",
    "Sleepy",
    "Mr Strong",
    "Mr Uppity",
    "Little Miss Sunshine",
    "Mr Impossible",
    "Mr Lazy",
    "Jack Jack",
    "Elastigirl",
    "Mr Greedy",
    "Mr Topsy Turvy",
    "Little Miss Fun",
    "Little Miss Magic",
    "Little Miss Trouble",
    "Pollyanna",
    "Pippy Longstocking",
    "Charles Dickens",
    "Oliver Twist",
    "Ian McEwan",
    "Agatha Christie",
    "Dr John Watson",
    "Mozart",
    "Rachmaninoff",
    "Tchaikovsky",
    "Beethoven",
    "Sibelius",
    "Vivaldi",
    "Celine Dion",
    "ABBA",
    "Pascal",
    "Vladimir Putin",
    "Simon Cowell",
    "Tim Peak",
    "Ed Sheeran",
    "David Attenborough",
    "Bill Gates",
    "Daniel Craig",
    "Tom Holland",
    "Emma Watson",
    "Serena Williams",
    "Usain Bolt",
    "Roger Federer",
    "Tiger Woods",
    "Lionel Messi",
    "Mo Farah",
    "Christopher Columbus",
    "Steven Hawkins",
    "Queen Elizabeth II",
    "Ernest Shackleton",
    "Alan Turing",
    "Jeff Bezos",
    "Dwayne Johnson",
    "Joe Biden",
    "Elon Musk",
    "LeBron James",
    "Robert Downey",
    "Cristiano Ronaldo",
    "Will Smith",
    "Justin Bieber",
    "Taylor Swift",
    "Mark Zuckerberg",
    "Opera Winfrey",
    "Meat Loaf",
    "Greta Thunberg",
    "Sir Captain Tom Moore",
    "Joe Wicks",
    "Jamie Oliver",
    "Donald Trump",
    "Richard Osman",
    "Alexander Armstrong",
    "Dan Walker",
    "Sally Nugent",
    "Carol Kirkwood",
    "Andrew Lloyd Webber",
    "Pope Francis",
    "Barack Obama",
    "Nelson Mandela",
    "Tom Cruise",
    "Tony Blair",
    "JK Rowling",
    "Kim Jong Un",
    "Malala Yousafzai",
    "Steve Jobs",
    "Hilary Clinton",
    "Prince William",
    "Lewis Hamilton",
    "Prince Harry",
    "Meghan Markel",
    "Roger Federer",
    "Roman Abramovich",
    "Melinda Gates",
    "Suzanne Collins",
    "Malorie Blackman",
    "Rick Riordan",
    "Enid Blyton",
    "Michael Morpurgo",
    "David Walliams",
    "RJ Palacio",
    "Jane Austen",
    "Arthur Ransome",
    "Anne Frank",
    "Amelia Earhart",
    "Lindsey Russel",
    "Rosa Parks",
    "Richard Bacon",
    "Adam Beales",
    "Richie Driss",
    "Robert Bob Belcher",
    "Mother Teresa",
    "Charles Darwin",
    "Albert Einstein",
    "Paul McCartney",
    "Thomas Edison",
    "Walt Disney",
    "Neil Armstrong",
    "John Lennon",
    "Adolf Hitler",
    "Madonna",
    "Ronald Reagan",
    "David Beckham",
    "Margaret Thatcher",
    "Florence Nightingale",
    "Tim Berners Lee",
    "Ant McPartlin",
    "Declan Donnelly",
    "Alesha Dixon",
    "Amanda Holden",
    "Diversity",
    "Lost voice guy",
    "Richard Jones",
    "Collin Thackery",
    "Napoleon Bonaparte",
    "Joan of Arc",
    "Isaac Newton",
    "Lewis Carroll",
    "Marco Polo",
    "John Cabot",
    "Ferdinand Magellan",
    "Sir Francis Drake",
    "Vasco de Gama",
    "Ed Stafford",
    "Jessica Watson",
    "Eric Larson",
    "David de Rothschild",
    "Andrew Skurka",
    "Frida Kahlo",
    "Emmeline Pankhurst",
    "Agent Fifi",
    "Mary Seacole",
    "Mary Anning",
    "Marie Curie",
    "Coco Chanel",
    "Gertrude Ederle",
    "Suffragettes",
    "Emma Carroll",
    "EB White",
    "Donald Trump",
    "JF Kennedy",
    "Abraham Lincoln",
    "George Washington",
    "Franklin Roosevelt",
    "George Bush",
    "Boris Johnson",
    "Theresa May",
    "David Cameron",
    "Gordon Brown",
    "Tony Blair",
  ],
  Action: [
    "Abide",
    "Absorb",
    "Admire",
    "Adore",
    "Adore",
    "Advance",
    "Advise",
    "Aid",
    "Alter",
    "Amble",
    "Amend",
    "Amplify",
    "Amuse",
    "Announce",
    "Arrive",
    "Ascend",
    "Ask",
    "Assault",
    "Attack",
    "Balloon",
    "Bargain",
    "Bash",
    "Batter",
    "Beam",
    "Beef",
    "Beg",
    "Bellow",
    "Blab",
    "Blabber",
    "Blast",
    "Blow",
    "Bluster",
    "Boast",
    "Bolt",
    "Boost",
    "Brew",
    "Brief",
    "Broadcast",
    "Brood",
    "Build",
    "Burrow",
    "Burst",
    "Bus",
    "Bust",
    "Calm",
    "Capture",
    "Cascade",
    "Cast",
    "Catapult",
    "Catch",
    "Chap",
    "Charge",
    "Chase",
    "Cherish",
    "Chip",
    "Chomp",
    "Clasp",
    "Cleave",
    "Climb",
    "Close",
    "Clutch",
    "Collide",
    "Command",
    "Comment",
    "Commune",
    "Conceal",
    "Confound",
    "Confuse",
    "Conspire",
    "Corrupt",
    "Cower",
    "Crackle",
    "Craft",
    "Crash",
    "Crave",
    "Crawl",
    "Create",
    "Creep",
    "Croak",
    "Crumple",
    "Crush",
    "Cry",
    "Dangle",
    "Dart",
    "Dash",
    "Dawdle",
    "Dazzle",
    "Deal",
    "Decay",
    "Deceive",
    "Declare",
    "Demand",
    "Demolish",
    "Depart",
    "Deposit",
    "Design",
    "Desire",
    "Despise",
    "Detect",
    "Deter",
    "Deviate",
    "Devour",
    "Dig",
    "Digest",
    "Diminish",
    "Dine",
    "Direct",
    "Disarm",
    "Discern",
    "Discover",
    "Disintegrate",
    "Dismantle",
    "Download",
    "Drag",
    "Drain",
    "Drip",
    "Drop",
    "Dwell",
    "Eavesdrop",
    "Encourage",
    "Engage",
    "Engulf",
    "Enjoy",
    "Enlarge",
    "Ensnare",
    "Envelop",
    "Erase",
    "Escort",
    "Evolve",
    "Excite",
    "Exhaust",
    "Exit",
    "Expand",
    "Explode",
    "Explore",
    "Expose",
    "Extend",
    "Extract",
    "Eyeball",
    "Ferment",
    "Fight",
    "Fish",
    "Fling",
    "Float",
    "Flounce",
    "Flourish",
    "Flow",
    "Fly",
    "Follow",
    "Forbid",
    "Force",
    "Frown",
    "Fumble",
    "Fuse",
    "Garble",
    "Gasp",
    "Gaze",
    "Gel",
    "Germinate",
    "Glare",
    "Gleam",
    "Glide",
    "Glisten",
    "Glitter",
    "Gloat",
    "Gobble",
    "Gorge",
    "Govern",
    "Grasp",
    "Gravitate",
    "Graze",
    "Grip",
    "Groan",
    "Grope",
    "Grow",
    "Growl",
    "Guffaw",
    "Guide",
    "Gush",
    "Gust",
    "Guzzle",
    "Hack",
    "Hail",
    "Halt",
    "Halt",
    "Harvest",
    "Heighten",
    "Hiccup",
    "Hiss",
    "Hobble",
    "Hold",
    "Holler",
    "Hope",
    "Hover",
    "Howl",
    "Huff",
    "Hurl",
    "Hurry",
    "Ignite",
    "Illuminate",
    "Imagine",
    "Impart",
    "Implore",
    "Impress",
    "Indulge",
    "Inflate",
    "Inhale",
    "Inquire",
    "Inspect",
    "Instruct",
    "Insult",
    "Intensify",
    "Intertwine",
    "Jab",
    "Jostle",
    "Journey",
    "Lament",
    "Lash",
    "Launch",
    "Leach",
    "Lead",
    "Leap",
    "Leave",
    "Level",
    "Liquefy",
    "Listen",
    "Loaf",
    "Loathe",
    "Lob",
    "Locate",
    "Look",
    "Lope",
    "Lounge",
    "Lull",
    "Lurch",
    "Lurk",
    "Magnify",
    "Manipulate",
    "Manufacture",
    "March",
    "Marvel",
    "Meander",
    "Mimic",
    "Mint",
    "Mix",
    "Moan",
    "Modify",
    "Morph",
    "Mount",
    "Multiply",
    "Munch",
    "Muse",
    "Mushroom",
    "Mystify",
    "Nap",
    "Neglect",
    "Nibble",
    "Notice",
    "Notify",
    "Nudge",
    "Obey",
    "Obtain",
    "Occupy",
    "Ooze",
    "Oppress",
    "Order",
    "Outrage",
    "Overrule",
    "Pacify",
    "Paint",
    "Park",
    "Peck",
    "Peek",
    "Peer",
    "Perceive",
    "Persuade",
    "Petrify",
    "Picture",
    "Pilot",
    "Pinpoint",
    "Place",
    "Plant",
    "Plead",
    "Plod",
    "Plop",
    "Plot",
    "Pluck",
    "Plunge",
    "Poison",
    "Poke",
    "Pop",
    "Position",
    "Power",
    "Prickle",
    "Prize",
    "Probe",
    "Prod",
    "Prune",
    "Pursue",
    "Question",
    "Quit",
    "Race",
    "Realize",
    "Recite",
    "Recoil",
    "Refashion",
    "Refine",
    "Relish",
    "Remove",
    "Reply",
    "Report",
    "Require",
    "Retreat",
    "Reveal",
    "Reverberate",
    "Revitalize",
    "Revolutionize",
    "Revolve",
    "Ride",
    "Rip",
    "Ripen",
    "Rise",
    "Roar",
    "Roll",
    "Ruin",
    "Run",
    "Rush",
    "Rust",
    "Saunter",
    "Scale",
    "Scamper",
    "Scan",
    "Scoff",
    "Scorch",
    "Scrape",
    "Scratch",
    "Scrawl",
    "Scream",
    "Scurry",
    "Seal",
    "Seize",
    "Serve",
    "Shatter",
    "Shave",
    "Shepherd",
    "Shimmer",
    "Shine",
    "Shock",
    "Shout",
    "Shriek",
    "Shrivel",
    "Shut",
    "Sigh",
    "Sink",
    "Sit",
    "Sizzle",
    "Skip",
    "Skive",
    "Skulk",
    "Slam",
    "Slash",
    "Slide",
    "Slink",
    "Slip",
    "Slump",
    "Slurp",
    "Smash",
    "Smite",
    "Smudge",
    "Snag",
    "Snap",
    "Snarl",
    "Sneak",
    "Snicker",
    "Snooze",
    "Snore",
    "Snowball",
    "Snuffle",
    "Soak",
    "Soar",
    "Soothe",
    "Spam",
    "Sparkle",
    "Spatter",
    "Speckle",
    "Speed",
    "Spew",
    "Sport",
    "Sprinkle",
    "Sprout",
    "Squeal",
    "Squeeze",
    "Stagger",
    "Stalk",
    "Stare",
    "Startle",
    "Starve",
    "Steal",
    "Steer",
    "Stir",
    "Storm",
    "Strain",
    "Stretch",
    "Stride",
    "Strip",
    "Stroke",
    "Stroll",
    "Struggle",
    "Stumble",
    "Supercharge",
    "Supersize",
    "Surge",
    "Survey",
    "Swell",
    "Swipe",
    "Swoon",
    "Tail",
    "Tangle",
    "Tattle",
    "Teach",
    "Teleport",
    "Toddle",
    "Transfigure",
    "Transform",
    "Travel",
    "Traverse",
    "Treasure",
    "Treat",
    "Trim",
    "Trip",
    "Trudge",
    "Tussle",
    "Type",
    "Uncover",
    "Undress",
    "Unearth",
    "Untangle",
    "Unveil",
    "Usher",
    "Utter",
    "Veil",
    "Venture",
    "Wail",
    "Wallow",
    "Wander",
    "Want",
    "Wave",
    "Wear",
    "Weave",
    "Whisper",
    "Wind",
    "Wish",
    "Withdraw",
    "Wreck",
    "Wrench",
    "Wrest",
    "Wrestle",
    "Wring",
    "Yank",
    "Yell",
    "Zap",
    "Zing",
  ],
  Random: [
    "Minecraft",
    "Mathematics",
    "Biology",
    "Chemistry",
    "Shuttlecock",
    "Oncology",
    "Pharmacy",
    "Laboratory",
    "Lavatory",
    "Bar chart",
    "Spreadsheet",
    "Microsoft",
    "Mario Kart",
    "Opaque",
    "Translucent",
    "Transparent",
    "Memory foam",
    "Gas",
    "Aerosol",
    "Butler",
    "Maid",
    "Lady",
    "Lord",
    "Jewellery Box",
    "Ceiling",
    "Minotaur",
    "Argonauts",
    "Green house",
    "Slytherin",
    "Ravenclaw",
    "Gryffindor",
    "Hufflepuff",
    "Astrology",
    "Death Eaters",
    "Dementors",
    "Unicorn",
    "The Great Gatsby",
    "October",
    "Kilo",
    "Micron ",
    "Shilling",
    "Ecclesiastes",
    "Psalms",
    "Proverbs",
    "Numbers",
    "Decimal point",
    "Dash",
    "Hyphen",
    "Semicolon",
    "Indigo",
    "Violet",
    "Navy blue",
    "Teal",
    "Duck egg blue",
    "Royal blue",
    "Crimson",
    "Pewter",
    "Yellow Ochre",
    "Elephants breath",
    "Offwhite",
    "Matt",
    "Gloss",
    "Algebra",
    "Jazz",
    "Soul",
    "Honky Tonk",
    "Staccato",
    "Timbre",
    "Tone",
    "Accent",
    "Dialect",
    "Bashful",
    "Magnum",
    "Happy",
    "Dopey",
    "Margherita",
    "Sloppy Guiseppe",
    "Nduja",
    "Hawaiian Pizza",
    "Masterchef",
    "Strictly come dancing",
    "Hyundai",
    "Kia",
    "Toyota",
    "Vauxhall",
    "Citroen",
    "Land Rover",
    "Bugatti",
    "Lotus",
    "Wholegrain",
    "Decaffeinated",
    "Heinz",
    "Dried figs",
  ],
}
